### ISSUE TITLE
HDMI don't work

### ISSUE THREAD

**Issue by olmostblue** [wgjas2/MSI-Prestige-15-Hackintosh#12]
Connecting an external monitor to the HDMI port does not show the image on the monitor.
I'm on Catalina, bootloader is OC

**Comment by wgjas2** [comment]
worked fine in my mechine, work at HDMI 2.0 3840x2160 60Hz

**Comment by gemini444** [comment]
> Connecting an external monitor to the HDMI port does not show the image on the monitor.
> I'm on Catalina, bootloader is OC

I have the almost same laptop (msi prestige 15 a10sc 1080p) and my HDMI is not working either. I can't find any solution yet. Both TB port works with type-c hdmi adapter.

**Comment by vomesk** [comment]
Solved.

Add or change:
Device Properties > PciRoot(0x0)/Pci(0x2,0x0) > AAPL,ig-platform-id = 0400A53E
Device Properties > PciRoot(0x0)/Pci(0x2,0x0) > device-id = A53E0000
Device Properties > PciRoot(0x0)/Pci(0x2,0x0) > framebuffer-con0-enable = 01000000
Device Properties > PciRoot(0x0)/Pci(0x2,0x0) > framebuffer-con0-flags = 98000000

Add in boot-args: -igfxblr agdpmod=vit9696
