### ISSUE TITLE
Big Sur支援4k@60Hz （Sharp SHP14A1 15.6' 3840x2160(4K)）

### ISSUE THREAD

**Issue by yorkweng** [wgjas2/MSI-Prestige-15-Hackintosh#15]
更新whatevergreen.kext到最新版，在boot-arg加入-igfxblr（v1.4.6要求）及-igfxmpc並把Deviceproperties中PciRoot(0x0)/Pci(0x2,0x0) 的 AAPL00,override-no-connect移除

**Comment by wgjas2** [comment]
感谢提醒，我已经尝试，更新WhatverGreen在DeviceProperties/PciRoot(0x0)/Pci(0x2,0x0)中按如下操作即可:
移除 AAPL00,override-no-connect
新增 enable-backlight-registers-fix    01000000
新增 enable-max-pixel-clock-override    01000000
后续会修改推送。

**Comment by bm0804** [comment]
可以更新一下吗 试了上面两种方法 内建显示器都不能正常启动

**Comment by bm0804** [comment]
> > 可以更新一下吗 试了上面两种方法 内建显示器都不能正常启动
> 
> 本子不在手上，过几天看看

感谢!
