### ISSUE TITLE
Installing problem

### ISSUE THREAD

**Issue by vaqif14** [wgjas2/MSI-Prestige-15-Hackintosh#2]
When going install after 2 minutes to finish laptop restarting. Could you help to fix it?

**Comment by wgjas2** [comment]
boot failed, to reboot and try again, if fail again....try more times...  and u should setting BIOS before install

**Comment by vaqif14** [comment]
I tried but my wifi card is gone :(

**Comment by wgjas2** [comment]
> I tried but my wifi card is gone :(

Install Apps/HeliPort.dmg to connect wifi.

**Comment by AndryX19** [comment]
Hey, nice work, first thanks for make this efi.
Second, did you know why show sometimes error "OCB: StartImage Failed". I note that happen when switch to Windows, but I'm not sure if is that the cause.
