### ISSUE TITLE
No audio after rebooting from windows 

### ISSUE THREAD

**Issue by vaqif14** [wgjas2/MSI-Prestige-15-Hackintosh#23]
All things work perfectly but only when the first time restart from windows switching to mac sound is missing could you fix pls?

**Comment by wgjas2** [comment]
It is a known issue and no solution…

**Comment by vaqif14** [comment]
Ok thanks you for reply

**Comment by hla63** [comment]
it could be resolve if you can make codec dump (Realtek driver and Microsoft driver) under windows with [RTHDDump](https://asus-linux.org/RtHDDump_V236.zip)

& compare the coefs values under Node 20 (Realtek driver vs Microsoft driver)
More explanation [here](https://github.com/acidanthera/AppleALC/pull/758) just an exemple for alc 1220
& [here](https://github.com/AndresGarciaSobrado91/MSI-Modern15-Hackintosh/discussions/4)
This method works with ALC 235 with my msi modern 15.

Mikebeaton actually works on a script to dump coef value under macOS.
