### ISSUE TITLE
安装monterey后，oc引导时键盘失灵？

### ISSUE THREAD

**Issue by yyxknight** [wgjas2/MSI-Prestige-15-Hackintosh#25]

**Comment by yyxknight** [comment]
oc界面无法选择，开机能进bios，但进bios后键盘也不能用，之前Big Sur一切正常

**Comment by aleixsr** [comment]
Hello, I had same issue using my EFI https://github.com/aleixsr/MSI-Prestige-15-A10SC-Hackintosh
Solution was to add Ps2KeyboardDxe.efi and enable it at boot.

Best Regards.

**Comment by yyxknight** [comment]
> Hello, I had same issue using my EFI https://github.com/aleixsr/MSI-Prestige-15-A10SC-Hackintosh Solution was to add Ps2KeyboardDxe.efi and enable it at boot.
> 
> Best Regards.

Thank you very much.I'll try your EFI file.
