### ISSUE TITLE
AX200 not working 

### ISSUE THREAD

**Issue by Yusepp** [wgjas2/MSI-Prestige-15-Hackintosh#3]
Im using newest kext and newest heliport but wifi is not working at all. Wifi do scan point access and connects to them but after that remains with an exclamation(!) sign. Other times wifi constantly switches from "turn on" to "turn off" and then again.

Did you know a fix?

**Comment by wgjas2** [comment]
Now I use BCM943602BAED(DW1830), I had no time to test AX200's new kext, you can find solution from official of itlwx.kext.
