### ISSUE TITLE
wifi and bluetooth stop working

### ISSUE THREAD

**Issue by AndryX19** [wgjas2/MSI-Prestige-15-Hackintosh#6]
Hi, first thank you for the new improvment in update, I check the last one and I notice that Wifi and bluetooth doesn't work, specially the itlwm kext don't be initialized. How fix that??
EDIT- Wifi fixed, need itlwm update (from here https://github.com/1hbb/OpenIntelWireless-Factory/releases )

**Comment by wgjas2** [comment]
already update
