### ISSUE TITLE
AX201版本的一些建議及請求

### ISSUE THREAD

**Issue by yorkweng** [wgjas2/MSI-Prestige-15-Hackintosh#7]
首先，感謝作者持續更新及改進此部電腦。
但有一點建議及兩點請求，希望作者能協助。
建議：
在此網站中https://github.com/OpenIntelWireless/itlwm
的AirportItlwm驅動可以驅動AX201網卡（WiFi 正常使用無需下載其它應用程式），但是airdrop目前無法使用等等bug還有待更新修正，目前遇到的問題只有WiFi 與藍牙一起使用時WiFi 似乎會有問題。
請求：
希望作者能讓Mac可以控制風扇轉速及F12鍵能夠讓螢幕有反轉的功能，另外我有裝Windows系統，在Windows系統中載入Creator Center似乎會有問題（被要求下載Dragon Center)這樣在Windows系統中也無法控制風扇轉速，遊戲玩起來會有些擔心CPU故障。

**Comment by AndryX19** [comment]
Hi, I open a issue post with same problem. If you look my issue post I mention the solution for wifi, anyway the problem of bluetooth and creator center still remain

**Comment by yorkweng** [comment]
Hi, AndryX19. I used Heliport on September 2nd, but this is only an application. It does not enable the built-in WiFi, so neither the map nor the search program can be used. In mid-to-late September, AirportItlwm was launched to drive the AX201 network card and support the built-in WiFi of Mac. In addition, you can also use the Handoff function and Airdrop (Airdrop has to wait to be repaired, but it has appeared on the Finder side bar normally), The built-in map and search can be used normally. The big problem for me currently is only when connecting my Airpods and WiFi at the same time, there will be WiFi connection problems.

**Comment by AndryX19** [comment]
Heliport is needed to drive itlwm.kext which comunicate with ax201, download itlwm kext from here and wifi go back to work (https://github.com/1hbb/OpenIntelWireless-Factory/releases).
For bluetooth I'm waiting for a fix or update, maybe an update like wifi kext risolve the problem with the newer opencore 0.6.2.
I'm not using airport and airdrop :D

**Comment by wgjas2** [comment]
> 首先，感謝作者持續更新及改進此部電腦。
> 但有一點建議及兩點請求，希望作者能協助。
> 建議：
> 在此網站中https://github.com/OpenIntelWireless/itlwm
> 的AirportItlwm驅動可以驅動AX201網卡（WiFi 正常使用無需下載其它應用程式），但是airdrop目前無法使用等等bug還有待更新修正，目前遇到的問題只有WiFi 與藍牙一起使用時WiFi 似乎會有問題。
> 請求：
> 希望作者能讓Mac可以控制風扇轉速及F12鍵能夠讓螢幕有反轉的功能，另外我有裝Windows系統，在Windows系統中載入Creator Center似乎會有問題（被要求下載Dragon Center)這樣在Windows系統中也無法控制風扇轉速，遊戲玩起來會有些擔心CPU故障。

1. Intel WiFi 并非苹果原生支持，目前的驱动是itlwm是爱好者根据OpenBSD驱动移植，稳定性和功能支持肯定是不如官方驱动的，如果需要完美的体验，建议跟我一样换成DW1830。
2. 关于风扇转速目前还没有办法，F12屏幕翻转功能可能需要较长时间研究，我工作比较忙没有足够的时间去研究这方面，目前只是满足自己工作需求，所以这些功能只能搁置了；至于Creator Center我在Windows中使用并无问题，风扇转速控制正常。
