### ISSUE TITLE
Black Screen installing Big Sur

### ISSUE THREAD

**Issue by Yusepp** [wgjas2/MSI-Prestige-15-Hackintosh#8]
I upgraded to Big Sur via AppStore, after the first reboot I tried your settings on my msi prestige 15 but in the second reboot im getting black screen. Catalina seetings keep freeze at apple logo. OC showns MACOS installer option so im still in the upgrading process. Any idea?

**Comment by yann5280** [comment]
Same here. Unable to boot from the usb installer
Made a bootable usb to perform clean installation of big sur.
It goes black screen when the progress bar of booting into installation is about 30%.

**Comment by wgjas2** [comment]
upgrade to Big Sur must use bigsur config, internal screen in big sur is unsupported 4K60Hz, must modify EDID to use 4K48Hz，I had modified my EDID in bigsur config already, if still black screen, perhaps your screen is not Sharp SHP14A1, use this to modify own EDID: [Link](https://gist.github.com/xxxzc/032bf9eef2f217bc7d60f087e25555e1), replacing config-> DeviceProperties -> Add -> PciRoot(0x0)/Pci(0x2,0x0) -> AAPL00,override-no-connect value.

**Comment by yann5280** [comment]
Yes, I am using a FHD panel
and it works fine. Thank you so much

**Comment by Yusepp** [comment]
> Yes, I am using a FHD panel
> and it works fine. Thank you so much

What value did you place into `replacing config-> DeviceProperties -> Add -> PciRoot(0x0)/Pci(0x2,0x0) -> AAPL00,override-no-connect` for fixing the FHD panel?

**Comment by yann5280** [comment]
> > Yes, I am using a FHD panel
> > and it works fine. Thank you so much
> 
> What value did you place into `replacing config-> DeviceProperties -> Add -> PciRoot(0x0)/Pci(0x2,0x0) -> AAPL00,override-no-connect ` for fixing the FHD panel?

Just delete the “AAPL00,override-no-connect” and leave it empty

**Comment by Yusepp** [comment]
It's working! Thanks , I will close the Issue.
